### ISSUE TITLE
lte function query / possible suggestion

### ISSUE THREAD

**Issue by StephenKay67** [LasseHjort/cuRe#2]
From looking at the “lts” function code the Ederer Cohort method for predicting expected survival at a nominated time point is used. Thus for the whole sample in lte argument “newdata” the function computes just one expected survival probability at that time point. The code then multiples this by the relative survival estimate (presume again this is a cohort estimate – likely mean estimate similar to the “meansurv” prediction for stpm2). Surely the resulting estimate is biased (unless common values apply to all)? A better estimate would be to compute all values at the individual level - i.e. if there are n rows in the (lte argument “newdata”)  data.frame, with each representing a patient then this expected survival * relative survival should be calculated for each appropriately then averaged. This seems quite possible given that the survival command survexp has an argument allowing such individual estimates (instead of cohort).  Please correct me if my reasoning/assumptions are wrong. Really nice package either way!

**Comment by LasseHjort** [comment]
Thanks a lot for the comment. I guess it depends on what you are aiming at. If you just want estimates of long-term survival in a cohort, I think it is reasonable to simply use the cohort relative survival and mulitply that with the cohort expected survival. Of cause, if you want to make individual predictions, the expected survival should differ between individuals. This is actually also done in the function. So if you add `newdata`, the function uses `survexp` to compute the expected survival corresponding to each row in `newdata`. 

I like your idea about the mean survival, which can be used as a kind of standardization. I have added an argument to the function, `mean`. If `mean=TRUE`, the function averages all survival predictions across the rows in `newdata`. However, currently it is not computing CIs or SEs as I do not think that these can be directly computed using the delta method. Maybe a bootstrapping procedure would be better and this is not so easily implemented in the function.

**Comment by StephenKay67** [comment]
Many thanks for looking into and adding feature. 
Appreciate problem with CIs/SE's - don't need for my purposes.
