### ISSUE TITLE
Extracting estimates for plotting

### ISSUE THREAD

**Issue by kurttaylor** [LasseHjort/cuRe#4]
How does one extract estimates from an object generated by `GenFlexCureModel` to plot? At the moment, I run my model:

`non_mcm_spl_3df <- GenFlexCureModel(formula = survival_formula,
                                    smooth.formula =  ~ ns(log(OStimey), df = 3),
                                    bhazard = data_nivo$bgmort,
                                    data = data_nivo,
                                    type = "nmixture")`

I am aware I can then plot this using `plot(non_mcm_spl_3df)` but I am running multiple models and wish to plot them using ggplot2. For example, if I run a model  using flexsurvcure like this:

`mcm_lnor_nivo = flexsurvcure(survival_formula, data = data_nivo, dist="lnorm", bhazard = data_nivo$bgmort, mixture = T, inits = c(0.1, mcm_lnor_temp_nivo$res[2:3,1]))`

I can then extract the estimates into a df ready for plotting:

`mcm_lnor_nivo = summary(mcm_fits$mcm_lnor_nivo, t=seq(0, 4, 0.08),type="survival",ci=F,tidy=T)`

Is this possible using GenFlexCureModel?

**Comment by kurttaylor** [comment]
Might be easier to understand my question here: https://stackoverflow.com/questions/76480448/how-to-extrapolate-using-cure-package-in-r

**Comment by LasseHjort** [comment]
Thanks for the question and apologies for the delayed answer. Please, see the answer on stackoverflow. Let me know, if you have any problems with this solution

**Comment by kurttaylor** [comment]
Thank you @LasseHjort - I am still a bit confused how to plot the extrapolation up to the desired time point - I have replied on Stack. Could you please clarify and provide example use the code I provided using the coldDC dataset? Many thanks for your help

**Comment by LasseHjort** [comment]
Hi! Just updated the my answer on stackoverflow. Hope this helps.
